### ISSUE TITLE
Crashing messages (SMS) and Control Center.

### ISSUE THREAD

**Issue by Jynx175** [PoomSmart/EmojiPort-10-Resources#1]
after the new update, everything crashes.

**Comment by Jynx175** [comment]
https://pastebin.com/X61xswq5

**Comment by Jynx175** [comment]
https://imgur.com/gallery/dP1gHNT video of crashing. This does not happen when i uninstall emojiport. 

Tweak list here - https://pastebin.com/ukLk51Rk

iOS version is 10.1.1, Extra_recipe.

**Comment by PoomSmart** [comment]
Fixed in version 1.0.4
