### ISSUE TITLE
Depends on com.ps.emojiport10resources

### ISSUE THREAD

**Issue by LilyMods** [PoomSmart/EmojiPort-10-Resources#4]
Despite having this installed, I cannot update emojiport because it returns this error. I tried uninstalling and now I can't reinstall it.

**Comment by LilyMods** [comment]
"Cannot find source to download a version of 1.5.1 of 'com.ps.emojiport10resources:iphones-arm"

**Comment by LilyMods** [comment]
![IMG_3868](https://github.com/PoomSmart/EmojiPort-10-Resources/assets/115035308/cccad83a-4bdd-42be-ae6d-89925da5b7cf)
![IMG_3869](https://github.com/PoomSmart/EmojiPort-10-Resources/assets/115035308/8ceeccdf-7490-4759-8e70-7c704021d8ad)

**Comment by GooglyBlox** [comment]
I'm experiencing the same issue as well

**Comment by PoomSmart** [comment]
Uploaded.
